[project]
name = "fastapi-blog"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Alex Huaracha", email = "129701149+Alex-Huaracha@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "aiosqlite>=0.22.1",
    "fastapi[standard]>=0.141.1",
    "greenlet>=3.5.5",
    "sqlalchemy>=2.0.52",
]
